SET LOCAL lock_timeout = '5s';--> statement-breakpoint
CREATE TABLE "twitch_follows" (
	"user_id" uuid NOT NULL,
	"streamer_id" integer NOT NULL,
	"notify_enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "twitch_follows_user_id_streamer_id_pk" PRIMARY KEY("user_id","streamer_id")
);
--> statement-breakpoint
CREATE TABLE "youtube_follows" (
	"user_id" uuid NOT NULL,
	"channel_id" text NOT NULL,
	"notify_enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "youtube_follows_user_id_channel_id_pk" PRIMARY KEY("user_id","channel_id")
);
--> statement-breakpoint
ALTER TABLE "youtube_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "youtube_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 2 CACHE 1);--> statement-breakpoint
ALTER TABLE "core_notifications" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "savings_entries" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "savings_goals" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "starrail_accounts" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "youtube_settings" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "youtube_translations" ADD COLUMN "requested_by" uuid;--> statement-breakpoint
ALTER TABLE "youtube_translations" ADD COLUMN "glossary" jsonb;--> statement-breakpoint
ALTER TABLE "twitch_follows" ADD CONSTRAINT "twitch_follows_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "twitch_follows" ADD CONSTRAINT "twitch_follows_streamer_id_twitch_streamers_id_fk" FOREIGN KEY ("streamer_id") REFERENCES "public"."twitch_streamers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "youtube_follows" ADD CONSTRAINT "youtube_follows_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "youtube_follows" ADD CONSTRAINT "youtube_follows_channel_id_youtube_channels_channel_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."youtube_channels"("channel_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "twitch_follows_streamer_id_idx" ON "twitch_follows" USING btree ("streamer_id");--> statement-breakpoint
CREATE INDEX "youtube_follows_channel_id_idx" ON "youtube_follows" USING btree ("channel_id");--> statement-breakpoint
ALTER TABLE "core_notifications" ADD CONSTRAINT "core_notifications_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "savings_entries" ADD CONSTRAINT "savings_entries_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "savings_goals" ADD CONSTRAINT "savings_goals_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "starrail_accounts" ADD CONSTRAINT "starrail_accounts_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "youtube_settings" ADD CONSTRAINT "youtube_settings_user_id_core_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."core_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "youtube_translations" ADD CONSTRAINT "youtube_translations_requested_by_core_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."core_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "core_notifications_user_created_at_idx" ON "core_notifications" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "core_notifications_user_unread_idx" ON "core_notifications" USING btree ("user_id","module") WHERE "core_notifications"."read_at" is null;--> statement-breakpoint
CREATE INDEX "savings_entries_user_id_idx" ON "savings_entries" USING btree ("user_id","month");--> statement-breakpoint
CREATE INDEX "savings_goals_user_id_idx" ON "savings_goals" USING btree ("user_id","sort_order");--> statement-breakpoint
CREATE INDEX "starrail_accounts_user_id_idx" ON "starrail_accounts" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "youtube_settings" ADD CONSTRAINT "youtube_settings_user_id_unique" UNIQUE("user_id");--> statement-breakpoint
-- 單人版留下的資料都歸給站長：最早建立的 owner，沒有 owner 時用最早建立的帳號；一個帳號都沒有時不動，新程式不讀 user_id 是 null 的列
INSERT INTO "twitch_follows" ("user_id", "streamer_id", "notify_enabled")
SELECT "owner"."id", "twitch_streamers"."id", "twitch_streamers"."notify_enabled"
FROM "twitch_streamers" CROSS JOIN (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) AS "owner"
ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "youtube_follows" ("user_id", "channel_id", "notify_enabled")
SELECT "owner"."id", "youtube_channels"."channel_id", "youtube_channels"."notify_enabled"
FROM "youtube_channels" CROSS JOIN (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) AS "owner"
ON CONFLICT DO NOTHING;--> statement-breakpoint
-- 翻譯的專有名詞表快照用單人版的設定：舊程式每一批都用它，接著翻的結果才會一致
UPDATE "youtube_translations" SET
  "requested_by" = (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1),
  "glossary" = COALESCE((SELECT "glossary" FROM "youtube_settings" WHERE "id" = 1), '[]'::jsonb)
WHERE "requested_by" IS NULL;--> statement-breakpoint
-- 單人版只寫 id = 1 這一列
UPDATE "youtube_settings" SET "user_id" = (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) WHERE "user_id" IS NULL AND "id" = 1;--> statement-breakpoint
UPDATE "starrail_accounts" SET "user_id" = (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) WHERE "user_id" IS NULL;--> statement-breakpoint
UPDATE "savings_goals" SET "user_id" = (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) WHERE "user_id" IS NULL;--> statement-breakpoint
UPDATE "savings_entries" SET "user_id" = (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) WHERE "user_id" IS NULL;--> statement-breakpoint
UPDATE "core_notifications" SET "user_id" = (SELECT "id" FROM "core_users" ORDER BY ("role" = 'owner') DESC, "created_at", "id" LIMIT 1) WHERE "user_id" IS NULL;
